
public class TextTransitionLvl8 {

    public static string lvl = "Level 08";
    public static string text1 = " Un véhicule autonome1 est un véhicule automobile apte à rouler, sur route ouverte, sans intervention d'un conducteur. Le but à terme est de développer un véhicule pouvant circuler en toute situation dans le trafic réel sur la voie publique sans intervention humaine. C'est une application typique du domaine de la robotique mobile dans laquelle de nombreux acteurs sont engagés. Néanmoins de nombreux problèmes techniques et légaux restent à résoudre2.  ";
    public static string text2 = "La notion de voiture autonome peut recouvrir aussi bien un véhicule totalement autonome ou bien un véhicule « semi-autonome » disposant de différents systèmes d'aide à la conduite automatisée, par exemple en ville ou sur autoroute, ou encore de système de stationnement automatisé.  ";
    public static string text3 =" Un véhicule autonome - qui peut être est un véhicule standard aménagé - est équipé de capteurs numériques (caméras, radars, sonars, lidars, etc.) dont les données sont traitées par des processeurs et des logiciels spécifiques :\n\n    avec la fusion de ces données, ces logiciels reconstituent la situation routière 3D par reconnaissance de formes (limites de chaussées, de voies, de véhicules, d'obstacles, de panneaux) et emploient des algorithmes d'intelligence artificielle pour décider de l'action à réaliser sur les commandes du véhicule ;\n    les actions décidées par logiciel sont réalisées par servocommandes sur le volant, l'accélérateur, le frein et diverses interfaces permettant l'engagement et le désengagement du mode conduite automatique.\n" ;
    public static string text4 = " Certains analystes estiment que le développement de ce type de véhicules pourrait chambouler l'industrie automobile mondiale, à travers un changement radical des modes de consommation. Alors qu'aujourd'hui de nombreux particuliers achètent des véhicules pour leur utilisation personnelle, le développement de services de transport (taxi) reposant sur une flotte de véhicules autonomes pourrait conduire à une réduction substantielle de ce type d'achats4. L'industrie automobile passerait alors progressivement d'une industrie de biens à une industrie de services, les véhicules restant la propriété de la compagnie de transport5.";
    public static string text5 = " En 2004, l'agence américaine de défense DARPA organise le DARPA Grand Challenge, un concours réservé aux voitures autonomes avec 1 million de dollars à la clé. Le circuit faisait 240 km et se trouvait dans le désert. Le but était d'arriver à destination en moins de dix heures. Cette année-là, aucun véhicule n'arriva à destination. Celui qui est allé le plus loin, « Sandstorm », s'arrêta au bout de douze kilomètres.\n\nL'année suivante, une nouvelle édition de ce Challenge eut lieu, avec cette fois une récompense doublée. Cinq équipes arrivèrent à destination dont quatre sous la limite des 10 heures. L'équipe de Stanford Racing remporta le prix avec un temps record de 6 heures et 53 minutes. ";
    public static string text6 = "Cinq États des États-Unis autorisent les véhicules autonomes sur leur territoire : le Nevada (depuis juin 2011), la Floride (depuis avril 2012), la Californie (depuis septembre 2012), le Michigan (fin 2013), et Washington (district de Columbia) (début 2013). Une dizaine d'États américains (dont New York, Hawaï, New Jersey, Oklahoma, etc.) envisagent également de légaliser ces véhicules en 201543. ";

}
